services:
  backend:
    build:
      context: ./backend
    container_name: archgen
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      SPRING_DATA_MONGODB_URI: ${DB_URL}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - archgen-network

networks:
  archgen-network:
    driver: bridge

