version: '3.8'

services:
  backend:
    build:
      context: ./Backend
    container_name: archgen-backend
    restart: unless-stopped
    environment:
      PORT: 8080
      MONGODB_URI: ${MONGODB_URI}
    expose:
      8080
    networks:
      - archgen-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        FRONTEND_BACKEND_URL: ${FRONTEND_BACKEND_URL}
        FRONTEND_CLERK_API_KEY: ${FRONTEND_CLERK_API_KEY}
    container_name: archgen-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - archgen-network

networks:
  archgen-network:
    driver: bridge




