services:
  backend:
    build:
      context: backend
    container_name: archgen
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      MONGODB_URI: ${MONGODB_URI}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - archgen-network

networks:
  archgen-network:
    driver: bridge

